
project:
  type: website
  output-dir: _site
  preview:
    browser: true

website:
  title: "ECO 230 â€” Section 12"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus/syllabus.qmd
      - text: "Slides"
        menu:
          - text: "Week 1"
            file: week01/week_01.qmd
          - text: "Week 2"
            file: week02/week_02.qmd
          - text: "Week 3"
            file: week03/week_03.qmd
      - text: "Homework"
        menu:
          - text: "Homework 1"
            file: week01/Homework_01.qmd
          - text: "Homework 2"
            file: week02/Homework_02.qmd
          - text: "Homework 3"
            file: week03/Homework_03.qmd


format:
  html:
    toc: false            # default for normal pages (we'll turn on ToC in syllabus.qmd only)
    number-sections: false
    css: styles/accessibility.css

execute:
  echo: false
  warning: false

editor: visual
